export const INIT_SOCKET = 'INIT_SOCKET';
export const INIT_SOCKET_SUCCESS = 'INIT_SOCKET_SUCCESS';
export const INIT_SOCKET_FAILED = 'INIT_SOCKET_FAILED';

export const REMOVE_SOCKET = 'REMOVE_SOCKET';